package com.carlos.marvelapp.models

data class ResultComic(
    val characters: Characters,
    val collectedIssues: List<Any>,
    val collections: List<Any>,
    val creators: Creators,
    val dates: List<Date>,
    val description: String,
    val diamondCode: String,
    val digitalId: Int,
    val ean: String,
    val events: EventsX,
    val format: String,
    val id: Int,
    val images: List<Image>,
    val isbn: String,
    val issn: String,
    val issueNumber: Int,
    val modified: String,
    val pageCount: Int,
    val prices: List<Price>,
    val resourceURI: String,
    val series: SeriesX,
    val stories: StoriesX,
    val textObjects: List<TextObject>,
    val thumbnail: ThumbnailX,
    val title: String,
    val upc: String,
    val urls: List<UrlX>,
    val variantDescription: String,
    val variants: List<Variant>
)